version: '3.4'

services:
  catalogdb:
    image: mongo


  basketdb:
    image: redis


  discountdb:
    image: postgres


  pgadmin:
    image: dpage/pgadmin4

  orderdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"

  
  rabbitmq:
    image: rabbitmq:3-management-alpine


  portainer:
    image: portainer/portainer-ce


  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalogue/Catalogue.API/Dockerfile


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile


  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Ordering.API/Dockerfile


  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateway/OcelotApiGw/Dockerfile


  purchase.aggregator:
    image: ${DOCKER_REGISTRY-}purchaseaggregator
    build:
      context: .
      dockerfile: ApiGateway/Purchase.Aggregator/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:








